// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndkptatuxorlkytjqqgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ka3B0YXR1eG9ybGt5dGpxcWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNTQwNDEsImV4cCI6MjA1MjYzMDA0MX0.IgJN34_jCSlrdPcwf-4V1PEHuV8zpmIJ-5XTs8fCoRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);